apiVersion: v1
kind: Service
metadata:
  name: ha_event_processor
  namespace: default
  labels:
    app: ha_event_processor
spec:
  type: ClusterIP
  selector:
    app: ha_event_processor
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  sessionAffinity: None

